services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.flet
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      APP_DATABASE_PATH: /app/data/app.db
      APP_PORT: 8000
      APP_SHOW_BROWSER: "false"
      FLET_FORCE_WEB_SERVER: "true"

